# Generated by Django 4.0.4 on 2022-07-29 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_imagenproducto_producto_modeloproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloproducto',
            name='producto',
        ),
    ]
