# Generated by Django 4.0.4 on 2022-07-29 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_modeloproducto_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloproducto',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modelo', to='product.product'),
            preserve_default=False,
        ),
    ]
