# Generated by Django 4.0.4 on 2022-08-01 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_modeloproducto_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseñoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diseño', models.FileField(upload_to='3D/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseño', to='product.product')),
            ],
        ),
    ]
