# Generated by Django 4.0.4 on 2022-08-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_diseñoproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.FileField(upload_to='3D/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='design', to='product.product')),
            ],
        ),
        migrations.DeleteModel(
            name='DiseñoProducto',
        ),
    ]
