# Generated by Django 4.0.4 on 2022-07-29 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_imagenproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagen', to='product.product'),
        ),
        migrations.CreateModel(
            name='ModeloProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.FileField(upload_to='3D/')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelo3D', to='product.product')),
            ],
        ),
    ]
